### ISSUE TITLE
ADFS to AzureAD App Migration Excel Files

### ISSUE THREAD

**Issue by zamarax** [Identity-Deployment-Guides/Identity-Deployment-Guides#5]
Hi All for 'ADFS to AzureAD App Migration' I perform the powershell commands required, get no errors, pull it all back locally to a workstation with excel however I don't get those beautified reports with a refresh button, instead I get just csv data (relative to my environment), is there something I'm missing? Or does it require specific versions of office to complete properly?

**Comment by ArvindHarinder1** [comment]
Did you download the template and add it to the c:/adfs folder as well? The power shell creates the CSVs and when you download the excel template and add it to the folder, that's when you get the report 

https://github.com/Identity-Deployment-Guides/Identity-Deployment-Guides/raw/master/ADFS%20to%20AzureAD%20App%20Migration/ADFS%20to%20AAD%20App%20Migration%20Report%20Template.xlsm

**Comment by zamarax** [comment]
Ok, that worked.

However that is not really and clearly documented anywhere, thanks for your help.
